spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/fydb?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  redis:
    host: localhost
    port: 6379
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.sl.fy.pojo
  mapper-locations: classpath:mapping/*.xml

logging:
  level.com.sl.*: debug
server:
  port: 8088

wechat:
  mpAppId:
  mpAppSecret:
wx:
  pay:
    appId:
    mchId:
    mchKey:
    subAppId:
    subMchId:
    keyPath:
  mp:
    configs:
      appId:
      secret:






